"""
Phase-03 Input Sources
REIMPLEMENTED-2026

Defines input sources and their trust zone mappings.
Input sources represent where data originates.

This module contains NO execution logic.
All input sources are immutable.
"""

from enum import Enum
from typing import Dict, Final

from python.phase03_trust.trust_zones import TrustZone


class InputSource(Enum):
    """
    Input sources in the system.
    
    Each input source maps to a trust zone.
    """
    HUMAN_INPUT = "human_input"
    """Input directly from human operator."""
    
    GOVERNANCE_DEFINED = "governance_defined"
    """Input from frozen governance artifacts."""
    
    SYSTEM_GENERATED = "system_generated"
    """Input generated by system components."""
    
    EXTERNAL_UNTRUSTED = "external_untrusted"
    """Input from external untrusted sources."""


# =============================================================================
# INPUT SOURCE TO TRUST ZONE MAPPING
# =============================================================================

_SOURCE_TO_ZONE: Final[Dict[InputSource, TrustZone]] = {
    InputSource.HUMAN_INPUT: TrustZone.HUMAN,
    InputSource.GOVERNANCE_DEFINED: TrustZone.GOVERNANCE,
    InputSource.SYSTEM_GENERATED: TrustZone.SYSTEM,
    InputSource.EXTERNAL_UNTRUSTED: TrustZone.EXTERNAL,
}


# =============================================================================
# INPUT SOURCE FUNCTIONS
# =============================================================================

def get_source_trust_zone(source: InputSource) -> TrustZone:
    """
    Get the trust zone for an input source.
    
    Args:
        source: The input source.
        
    Returns:
        The TrustZone corresponding to this source.
    """
    return _SOURCE_TO_ZONE[source]


def get_all_input_sources() -> Dict[str, InputSource]:
    """
    Get all defined input sources.
    
    Returns:
        Dictionary mapping source names to InputSource values.
    """
    return {source.name: source for source in InputSource}
