"""
wireguard_config.py — WireGuard Auto-Configuration Script

Only runs AFTER device certificate is issued.
Reads device cert and generates wg0.conf.

NO config without valid certificate.
Authority pushes config only after cert issuance.
"""

import json
import os
import sys
import time

# =========================================================================
# PATHS
# =========================================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CERT_PATH = os.path.join(PROJECT_ROOT, 'storage', 'certs', 'device_cert.json')
WG_CONFIG_PATH = os.path.join(PROJECT_ROOT, 'config', 'wg0.conf')
PRIVATE_KEY_PATH = os.path.join(
    PROJECT_ROOT, 'config', 'device_identity', 'device_private.key')
PUBLIC_KEY_PATH = os.path.join(
    PROJECT_ROOT, 'config', 'device_identity', 'device_public.key')

# =========================================================================
# AUTHORITY ENDPOINT (configurable via env)
# =========================================================================

AUTHORITY_ENDPOINT = os.environ.get(
    'YGB_AUTHORITY_ENDPOINT', '10.0.0.1:51820')
AUTHORITY_PUBLIC_KEY = os.environ.get(
    'YGB_AUTHORITY_PUBKEY', '')
WG_LISTEN_PORT = 51820
WG_DNS = '10.0.0.1'


# =========================================================================
# CERTIFICATE VALIDATION
# =========================================================================

def load_certificate() -> dict:
    """Load and validate device certificate."""
    if not os.path.exists(CERT_PATH):
        print("[WG-CONFIG] ERROR: No device certificate found.")
        print(f"           Expected at: {CERT_PATH}")
        print("           Run device bootstrap first.")
        sys.exit(1)

    with open(CERT_PATH, 'r') as f:
        cert = json.load(f)

    required_fields = ['device_id', 'role', 'mesh_ip', 'issued_at',
                       'expires_at', 'signature']
    missing = [f for f in required_fields if f not in cert]
    if missing:
        print(f"[WG-CONFIG] ERROR: Certificate missing fields: {missing}")
        sys.exit(1)

    # Check expiry
    if cert['expires_at'] < int(time.time()):
        print("[WG-CONFIG] ERROR: Device certificate has expired.")
        print("           Re-run device bootstrap to get a new certificate.")
        sys.exit(1)

    return cert


def load_private_key() -> str:
    """Load device private key."""
    if not os.path.exists(PRIVATE_KEY_PATH):
        print("[WG-CONFIG] ERROR: No device private key found.")
        sys.exit(1)
    with open(PRIVATE_KEY_PATH, 'r') as f:
        return f.read().strip()


# =========================================================================
# WIREGUARD CONFIGURATION GENERATION
# =========================================================================

def generate_wg_config(cert: dict, private_key: str) -> str:
    """Generate wg0.conf contents."""
    mesh_ip = cert['mesh_ip']
    device_id = cert['device_id']

    config = f"""# WireGuard Configuration — Auto-generated by device bootstrap
# Device ID: {device_id}
# Role: {cert['role']}
# Generated: {int(time.time())}
# Expires: {cert['expires_at']}
#
# DO NOT EDIT MANUALLY. Re-run bootstrap to regenerate.

[Interface]
PrivateKey = {private_key}
Address = {mesh_ip}/24
ListenPort = {WG_LISTEN_PORT}
DNS = {WG_DNS}

[Peer]
# Authority Node
PublicKey = {AUTHORITY_PUBLIC_KEY}
Endpoint = {AUTHORITY_ENDPOINT}
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
"""
    return config


def write_wg_config(config: str):
    """Write WireGuard configuration file."""
    os.makedirs(os.path.dirname(WG_CONFIG_PATH), exist_ok=True)
    with open(WG_CONFIG_PATH, 'w') as f:
        f.write(config)

    # Restrict permissions
    if os.name != 'nt':
        os.chmod(WG_CONFIG_PATH, 0o600)

    print(f"[WG-CONFIG] Configuration written to: {WG_CONFIG_PATH}")


# =========================================================================
# MAIN
# =========================================================================

def main():
    print("\n========================================")
    print("  WireGuard Auto-Configuration")
    print("========================================\n")

    # Step 1: Load and validate certificate
    print("[WG-CONFIG] Loading device certificate...")
    cert = load_certificate()
    print(f"  Device ID: {cert['device_id'][:16]}...")
    print(f"  Role: {cert['role']}")
    print(f"  Mesh IP: {cert['mesh_ip']}")

    # Step 2: Load private key
    print("[WG-CONFIG] Loading device private key...")
    private_key = load_private_key()
    print("  Private key: loaded")

    # Step 3: Generate config
    print("[WG-CONFIG] Generating wg0.conf...")
    config = generate_wg_config(cert, private_key)
    write_wg_config(config)

    # Step 4: Log result
    print("\n[WG-CONFIG] ✅ WireGuard configured successfully.")
    print(f"  Interface: wg0")
    print(f"  Address: {cert['mesh_ip']}/24")
    print(f"  Authority: {AUTHORITY_ENDPOINT}")

    if not AUTHORITY_PUBLIC_KEY:
        print("\n[WG-CONFIG] ⚠️  YGB_AUTHORITY_PUBKEY not set.")
        print("  Set it to the authority's WireGuard public key.")

    print("\nTo activate WireGuard:")
    if os.name == 'nt':
        print("  Import wg0.conf into WireGuard client")
    else:
        print("  sudo wg-quick up config/wg0.conf")


if __name__ == '__main__':
    main()
